on:
  push

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Run python code
        run: |
          ls -lrt
          python3 main.py
  
    
