on:
  pull_request_target

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: action/checkout@v3
        
      - name: run application
        run: |
          ls -lrt
          python3 ../main.py
  
    
